[features]
seeds = false
skip-lint = false
[programs.localnet]
swap_token_solana = "AUHGCt7m2mvhVYmY5JF3aFKZnZ7dDJNcHNbo2Ni7VXWo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/anhtuanpc/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
