[features]
seeds = false
skip-lint = false
[programs.localnet]
swap_token_solana = "9ByBv1L1SRp8tNDLu9rEv67NnYcVnuQ9xzPFQGWKtFUj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/anhtuanpc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
