[features]
seeds = false
skip-lint = false
[programs.localnet]
swap_token_solana = "F9FoUdonDRvVE7S4ZbXCAV9PHtyGP9cgmvZEPeDfjbzN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/anhtuanpc/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
